### ISSUE TITLE
multi-line keyvalues

### ISSUE THREAD

**Issue by G2Pavon** [Erty-Gamedev/multi-entity-report.py#1]
For some strange reason sometimes the entity string has multi-line keyvalues, idk if bsp files support it or maybe it's related to how entity lump is unpacked. Here are two example maps (cs 1.6 bunny hop maps): 

[kzlt_arabhop.zip](https://github.com/user-attachments/files/17092114/kzlt_arabhop.zip)
[rush_qubish.zip](https://github.com/user-attachments/files/17092115/rush_qubish.zip)

for example rush_qubish.bsp has the following entity string, where _light key has multi-line value:

{
"origin" "2110 528 1920"
"_light" "75 143 146
 100"
"style" "0"
"_fade" "1.0"
"_falloff" "0"
"angles" "0 90 0"
"classname" "light"
}

so after using splitlines() `100"`  is treated as a different line.
then `line.split('"') ` is `['', '_light', ' ', '75 143 146']` instead of `['', '_light', ' ', '75 143 146 100', '']`
and next line is `['100', '']`

https://github.com/Erty-Gamedev/multi-entity-report.py/blob/ec1f0ee41be607cfbe547f663f1ade0ae9aec25d/bspentreader.py#L51-L67

i only found that behavior on _light keys

**Comment by Erty-Gamedev** [comment]
That's very strange, non-escaped linebreaks in entity values is definitely not standard. Were both these maps created by the same author?

Regardless I can rewrite that method to not rely on linebreaks, would make it more robust against this sort of things.
Thanks for the report!

**Comment by Erty-Gamedev** [comment]
Updated the script to handle linebreaks in value fields

**Comment by G2Pavon** [comment]
thanks for updating and for doing it quickly!

maps are from different authors, arabhop date from 2009 and qubish from 2019.
https://kz-rush.ru/en/maps/cs16/kzlt_arabhop
https://kz-rush.ru/en/maps/cs16/rush_qubish

btw i exported the .ent file with newbspguy and the multi-line value is not even exported:

```plaintext
{
"origin" "2110 528 1920"
"_light" "75 143 146
"
"style" "0"
"_fade" "1.0"
"_falloff" "0"
"angles" "0 90 0"
"classname" "light"
}
```

so apparently bsp files support multi-line key values?

**Comment by Erty-Gamedev** [comment]
The final quotation mark for the `_light` key was on the next line, but the fourth value of that list was missing.
![image](https://github.com/user-attachments/assets/051553ef-a476-424d-a4cb-27677284c000)

I'm guessing NewBSPGuy might have had issues parsing the value?

As for the BSP format, the format itself has no rules for entity keys or values. Only the compilers and the game sets any rules, which for the most part just expects each entity to be enclosed by curly brackets, with some number of key-value pairs enclosed in double-quotation marks in-between (and max 32 characters for the key, and 1024 characters for the value).
